### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by RockyLin** [saki4510t/AudioVideoRecordingSample#14]
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaCodec.getFormatNative(MediaCodec.java)
       at android.media.MediaCodec.getOutputFormat(MediaCodec.java:2515)
       at com.BattleAppLLC.BattleApp.view.squarevideo.encoder.MediaEncoder.drain(MediaEncoder.java:303)
       at com.BattleAppLLC.BattleApp.view.squarevideo.encoder.MediaEncoder.run(MediaEncoder.java:129)
       at java.lang.Thread.run(Thread.java:818)

![screen shot 2017-01-19 at 3 52 49 pm](https://cloud.githubusercontent.com/assets/6820710/22098086/63d6d16e-de5f-11e6-8eea-ceb3a49bc91f.png)

**Comment by lamster2018** [comment]
same question，any solution？
